"""third Migration

Revision ID: f417d645819c
Revises: fa1954f63252
Create Date: 2019-06-03 12:14:21.255913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f417d645819c'
down_revision = 'fa1954f63252'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('posted_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_posts_posted_at'), 'posts', ['posted_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posts_posted_at'), table_name='posts')
    op.drop_column('posts', 'posted_at')
    # ### end Alembic commands ###
